### ISSUE TITLE
CISv2 - ClusterScan is seen in Failed state when there are no failures in the scan

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#12]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a ClusterScan CR and give in invalid value of `scanProfileName`
- The scan is currently stuck in "In progress" state
- Edit the clusterScan CR and give in the correct `scanProfileName: rke-profile-permissive`
- The scan run finishes, but the Cluster Scan is seen in "Failed state"

```
spec:
  scanProfileName: rke-profile-permissive
status:
  conditions:
  - lastUpdateTime: "2020-08-31T19:41:42Z"
    status: "True"
    type: Stalled
  - lastUpdateTime: "2020-08-31T20:36:39Z"
    status: "True"
    type: Created
  - lastUpdateTime: "2020-08-31T20:36:49Z"
    status: "True"
    type: RunCompleted
  - lastUpdateTime: "2020-08-31T20:36:49Z"
    status: "True"
    type: Complete
  - status: Unknown
```

**Expected Result:**
ClusterScan should be in Pass/Active state

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `8d9cedde93`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom - 8 nodes - 3 etcd, 2 control and 3 worker nodes
- Kubernetes version (use `kubectl version`):

```
1.18
```

**Comment by prachidamle** [comment]
This issue has been fixed and available to test via the new tag:    
- repository: rancher/cis-operator
- tag: v0.0.4
- The rancher-cis-benchmark chart has been updated to use this tag. https://github.com/rancher/charts/pull/586


Fix provided:
- The conditions under the ClusterScan.Status field will be cleared when the scanProfileName is corrected and a new scan is launched. This will update the state of the ClusterScan correctly. 

Example: Here is how the clusterscan fields will be displayed that shows the CLUSTERSCANPROFILE used and the STATUS field will reflect the state of the scan as (pass/fail/error/reporting)

```
$ kubectl --kubeconfig ~/.kube/test_config_master  get clusterscans 

NAME           STATUS   CLUSTERSCANPROFILE       TOTAL   PASS   FAIL   SKIP   NOT APPLICABLE   LASTRUNTIMESTAMP
rke-cis        fail     rke-profile-hardened     92      59     13     0      20               2020-09-05T01:18:28Z
rke-cis-perm   pass     rke-profile-permissive   92      58     0      0      34               2020-09-05T01:19:36Z

```

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `3ca11da829 `**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart`. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
- Create a ClusterScan CR and give in invalid value of scanProfileName
- The scan is currently stuck in "In progress" state
- Edit the clusterScan CR and give in the correct scanProfileName: rke-profile-permissive
- The scan run finishes, but the Cluster Scan is seen in state `Pass` but with a `red` background color.

**Expected Result:**
The background color of the state `Pass` should NOT be red. Logging a separate issue to track this. - https://github.com/rancher/cis-operator/issues/23
