### ISSUE TITLE
CISv2 scan having failures is shown as Active on Dashboard UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#14]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Repo: `https://github.com/prachidamle/charts.git` branch: `civ-v2-chart`
- Run a CIS 1.5 hardened scan on a cluster (failures expected as a hardening step was not run on the cluster)
- Test 5.3.2 fails.
- But the ClusterScan is in "Active" state

```
spec:
  scanProfileName: rke-profile-hardened
status:
  conditions:
  - lastUpdateTime: "2020-08-31T19:29:50Z"
    status: "True"
    type: Created
  - lastUpdateTime: "2020-08-31T19:30:01Z"
    status: "True"
    type: RunCompleted
  - lastUpdateTime: "2020-08-31T19:30:01Z"
    status: "True"
    type: Complete
  - status: Unknown
    type: Alerted
  lastRunTimestamp: 2020-08-31 19:29:50.323980787 +0000 UTC m=+652.114686434
  observedGeneration: 1
  summary:
    fail: 1
    notApplicable: 20
    pass: 71
    skip: 0
    total: 92

```
- ClusterScanReport is also in "Active" state

**Expected Result:**
Cluster scan should be seen in "Failed" state

@prachidamle Question: Should we have the status of the corresponding cluster scan report also in "Failed" state? 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - 8d9cedde931
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom cluster 8 nodes
- Kubernetes version (use `kubectl version`):

```
1.18
```

**Comment by prachidamle** [comment]
This issue has been fixed and available to test via the new tag:    
- repository: rancher/cis-operator
- tag: v0.0.4
- The rancher-cis-benchmark chart has been updated to use this tag. https://github.com/rancher/charts/pull/586


Fix provided:
- A new `status.display.state` field has been added to the ClusterScan CRD and this will contain the state of the ClusterScan: pass/fail/error/reporting.
This state will be displayed under STATUS column of the ClusterScan list on Dashboard.

Example: Here is how the clusterscan fields will be displayed that shows the the STATUS field to reflect the state of the scan as (pass/fail/error/reporting)

```
$ kubectl --kubeconfig ~/.kube/test_config_master  get clusterscans 

NAME           STATUS   CLUSTERSCANPROFILE       TOTAL   PASS   FAIL   SKIP   NOT APPLICABLE   LASTRUNTIMESTAMP
rke-cis        fail     rke-profile-hardened     92      59     13     0      20               2020-09-05T01:18:28Z
rke-cis-perm   pass     rke-profile-permissive   92      58     0      0      34               2020-09-05T01:19:36Z
run-eks-1.0    error 

```
The STATE field on Dashboard should reflect this `status.display.state` value

**Comment by sowmyav27** [comment]
**On master-head - commit id: `76c26fb0f9 `**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart`. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
- Run a hardened rke scan on a default custom RKE cluster
- Scan shows state `Fail`.
<img width="1438" alt="Screen Shot 2020-09-07 at 11 34 51 AM" src="https://user-images.githubusercontent.com/26032343/92411815-3df44700-f0fe-11ea-95a5-f6009b935762.png">
- Scan report is in Active state.
