### ISSUE TITLE
Error annotating self pod

### ISSUE THREAD

**Issue by nicusor-serban-fourthline** [rancher/cis-operator#149]
Hello! I've deployed the cis-operator and cis-operator-crd through the chart to an EKS cluster and when I'm trying to run:
```
---
apiVersion: cis.cattle.io/v1
kind: ClusterScan
metadata:
  name: run-eks-1.0
spec:
  scanProfileName: "" # eks-profile
```
In the pod ` k logs -f security-scan-runner-run-eks-1.0-vq5tk` it's throwing an error then exiting with:
```
++ kubectl -n cis-operator-system annotate pod security-scan-runner-run-eks-1.0-zcmd6 field.cattle.io/sonobuoyDone=
error: --overwrite is false but found the following declared annotation(s): 'field.cattle.io/sonobuoyDone' already has a value (true)
++ echo 'error annotating self pod'
error annotating self pod
```

I did try with some older versions of the security scan runner but it ends up the same.

Thanks!

Edit: It sometimes works so this may be a race condition.

Edit: I think the above error also affects the results and `spec.skipTests` seems to be completely ignored.

<details>
  <summary>ClusterScanProfile</summary>
  
  ```yaml
  apiVersion: cis.cattle.io/v1
kind: ClusterScanProfile
metadata:
  annotations:
    meta.helm.sh/release-name: cis-operator
    meta.helm.sh/release-namespace: cis-operator-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: custom-eks-profile
spec:
  benchmarkVersion: eks-1.0
  skipTests:
    - 2.1.1
    - 4.1.1
    - 4.1.2
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.1.6
    - 4.2.1
    - 4.2.2
    - 4.2.3
    - 4.2.4
    - 4.2.5
    - 4.2.6
    - 4.2.7
    - 4.2.8
    - 4.2.9
    - 4.3.1
    - 4.3.2
    - 4.4.1
    - 4.4.2
    - 4.5.1
    - 4.6.1
    - 4.6.2
    - 4.6.3
    - 4.6.4
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.1.4
    - 5.2.1
    - 5.3.1
    - 5.4.1
    - 5.4.2
    - 5.4.3
    - 5.4.4
    - 5.4.5
    - 5.5.1
    - 5.6.1
  ```
  
</details>

---

<details>
  <summary>ClusterScan</summary>
  
  ```yaml
  ---
apiVersion: cis.cattle.io/v1
kind: ClusterScan
metadata:
  name: run-eks-1.0.1
spec:
  scanProfileName: "custom-eks-profile"
#  scheduledScanConfig:
#    cronSchedule: "0 7 * * *"
  ```
  
</details>
