### ISSUE TITLE
CIS App does not install if cluster name is a number

### ISSUE THREAD

**Issue by rancher-max** [rancher/cis-operator#152]
**Description:**
If the cluster name in rancher is just a number (for example: 122) then the CIS App fails to install with the following error message:
```
Error: UPGRADE FAILED: failed to create resource: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 1, error found in #10 byte of ...|,"value":122}],"imag|..., bigger context ...|,"value":"false"},{"name":"CLUSTER_NAME","value":122}],"image":"rancher/cis-operator:v1.0.7","imageP|... 
```

Note that the `rancher-cis-benchmark-crd` successfully installs, but `rancher-cis-benchmark` fails.

**Steps to Reproduce:**
1. Create a k3s cluster
2. Import the cluster into rancher, ensuring to give the Cluster Name as a number like "122"
3. Attempt to install the CIS Benchmark app.

**Version Info:**
Rancher: v2.6.4
Cluster type: Imported, k3s (all versions)

CIS Benchmark App Version: 2.0.3
```
affinity: {}
alerts:
  enabled: false
  metricsPort: 8080
  severity: warning
global:
  cattle:
    clusterName: ''
    systemDefaultRegistry: ''
  kubectl:
    repository: rancher/kubectl
    tag: v1.20.2
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.7
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.6
  sonobuoy:
    repository: rancher/mirrored-sonobuoy-sonobuoy
    tag: v0.53.2
nodeSelector: {}
resources: {}
tolerations: []
```
