### ISSUE TITLE
EPIC: CIS v2

### ISSUE THREAD

**Issue by maggieliu** [rancher/cis-operator#16]
Sub-tasks for this Epic:

- Clusterscan Operator to run Jobs to scan a cluster(https://github.com/rancher/rancher/issues/28392)
- ClusterScanProfiles and custom profiles (https://github.com/rancher/rancher/issues/28393)
- ClusterScanReport CR (https://github.com/rancher/rancher/issues/28396)
- Support scanning EKS/GKE clusters (https://github.com/rancher/rancher/issues/28398)

Following are moved out to 2.5.x
- Alerts (https://github.com/rancher/rancher/issues/28397)
- Customize benchmark configs (https://github.com/rancher/rancher/issues/28402)
- Scheduled ClusterScan (https://github.com/rancher/rancher/issues/28395)

**Comment by sowmyav27** [comment]
**On master-head - commit id: e919796c**

- As a standard user Deployed CIS benchmark chart on a user cluster. images:
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.5
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.0
  sonobuoy:
    repository: rancher/sonobuoy-sonobuoy
    tag: v0.16.3
```
- User is able to deploy cluster scans - RKE/EKS/GKE clusters.
- Clusterscanprofiles, cluster scans and ClusterScanReports CRs are available
- Separate issues have been logged to tracks issues related to any of ^^^
- Closing the epic
