### ISSUE TITLE
ClusterRoles for cis-operator and scan job pods are too permissive

### ISSUE THREAD

**Issue by atoy3731** [rancher/cis-operator#165]
## Issue

The existing ClusteRoles ([here](https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-cis-benchmark/2.1.0/templates/rbac.yaml)) attached to the ServiceAccounts are too permissive and can be used to destroy a cluster if a custom profile with exploitable audit commands is imported. For instance:

```
    groups:
    - id: exploitable-controle
      text: ""
      checks:
        - id: exploitable-check
          text: ""
          audit: >
            kubectl delete ns kube-system
```

## Potential Solution

In the Helm chart, the roles attached to the SAs should be scope down to specific required functions. We've been testing and these roles seem to work pretty well for all existing scans + custom scans:

#### Operator ClusterRole and Role
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cis-operator-clusterrole
rules:
- apiGroups:
  - "cis.cattle.io"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "pods"
  - "services"
  - "configmaps"
  - "nodes"
  verbs:
  - "list"
  - "create"
  - "update"
  - "watch"
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "list"
  - "create"
  - "update"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cis-operator-role
  namespace: cis-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "watch"
  - "list"
  - "get"
  - "patch"
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "watch"
  - "list"
  - "get"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  - "pods"
  verbs:
  - "watch"
  - "list"
  - "get"
  - "delete"
```

#### Scan ClusterRole & Role
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cis-scan-clusterrole
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "list"
  - "describe"
  - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cis-scan-role
  namespace: cis-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "patch"
  - "get"
  - "list"
  - "describe"
- apiGroups:
  - "apps"
  resources:
  - "daemonsets"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  verbs:
  - "update"
  - "create"
```
