### ISSUE TITLE
User defined Profile for CIS Scan

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#18]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

Currently behavior in Rancher:
```
- By default, "Permissive" run contains Rancher recommended skip tests and it cannot be unskipped.
- By default, "Hardened" run contains no skipped tests
- User can select either profile to run a CIS scan
- - If there are user skipped tests it will be applied on top of the profile selected.
```
As we have 2 pre defined profiles. Users should have ability to create his own profile, where he can define his own set of pre defined skip tests

**Comment by sowmyav27** [comment]
**On master-head - commit id: `3ca11da829 `**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart`. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```

- User is able to provide a custom scan profile by giving in the `benchmarkVersion` and `skipTests` details in the scanprofile CR
```
apiVersion: cis.cattle.io/v1
kind: ClusterScanProfile
metadata:
  name: #string
#  annotations:
#    key: string
#  labels:
#    key: string
#  namespace: string
spec:
#  benchmarkVersion: string
#  skipTests:
#
```
