### ISSUE TITLE
Hardened RKE2 cluster is not passing CIS scan with `rke2-cis-1.23-profile-hardened` profile

### ISSUE THREAD

**Issue by josedev-union** [rancher/cis-operator#196]
## Description
I deployed a downstream cluster following the rke2 hardening guide https://ranchermanager.docs.rancher.com/pages-for-subheaders/rke2-hardening-guide.
```
spec:
  defaultPodSecurityAdmissionConfigurationTemplateName: rancher-restricted
  rkeConfig:
    machineSelectorConfig:
      - config:
          profile: cis-1.23
          protect-kernel-defaults: true
```
Then I tried CIS scan using `rke2-cis-1.23-profile-hardened` profile following this guide https://ranchermanager.docs.rancher.com/pages-for-subheaders/cis-scan-guides.
But have 7 failed scans.
![image](https://github.com/rancher/cis-operator/assets/70741025/5ebe7428-592a-4614-93fe-8e78c86473b6)

First, I am wondering if this result is positive false or negative false. 
If this is correct result, hardening process has some missing parts? 
Or mismatching betwen CIS benchmark version and rke2 version could be the reason?
I tried `cis-1.23-profile` for CIS scan also, but the result is worse. 17 Fail, 45 Warn

## Versions
management cluster: rke2 1.25.7
rancher version: 2.7.3
downstream cluster: rke2 1.25.7
rancher-cis-benchmark app version: 4.0.0

## Actual results and expected results
- Actual results: 28 Warn, 7 Fail (see above screenshot plz)
- Expected result: 0 Warn, 0 Fail

PS: Please correct me if I filed the issue in the wrong place.
