### ISSUE TITLE
Customize variables paths and binaries for rke, rke2 and k3s in their own `config.yaml`

### ISSUE THREAD

**Issue by andypitcher** [rancher/cis-operator#211]
[kube-bench](https://github.com/aquasecurity/kube-bench) relies on a central configmap `config.yaml` that defines several variables (ex: `$kubeconfig`, `$kubeletconfig`) to execute a given scan (found in cfg/config.yaml). By default, kube-bench will test all the values appropriate for each variable, and will use the first existing occurrence.

In the case of $kubeconfig, if the path `/etc/kubernetes/kubelet.conf` is found on the node, it will use this to run the test id.

For example, in K3s profiles, some tests `audit` use  absolute path instead of a variable:

**k3s-cis-1.7-permissive/node.yaml:**

```
      - id: 4.1.3
        text: "If proxy kubeconfig file exists ensure permissions are set to 600 or more restrictive (Manual)"
        audit: 'stat -c %a /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig'
        tests:
          bin_op: or
          test_items:
            - flag: "permissions"
              set: true
              compare:
                op: bitmask
                value: "600"
```

**cis-1.7/node.yaml:**

```
      - id: 4.1.3
        text: "If proxy kubeconfig file exists ensure permissions are set to 600 or more restrictive (Manual)"
        audit: '/bin/sh -c ''if test -e $proxykubeconfig; then stat -c permissions=%a $proxykubeconfig; fi'' '
        tests:
          bin_op: or
          test_items:
            - flag: "permissions"
              set: true
              compare:
                op: bitmask
                value: "600"
```

It would preferable to remove these absolute paths/values and configure them directly in each distro's config.yaml, `k3s-cis-1.7-permissive/config.yaml`, so keep the test generic and isometric with kube-bench. 

For k3s's config.yaml, this could be the `proxy` part which will make `$proxykubeconfig = /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig`:

```
  proxy:
    optional: true
    bins:
      - "containers"
    kubeconfig:
      - "/var/lib/rancher/k3s/agent/kubeproxy.kubeconfig"
    defaultkubeconfig: "/var/lib/rancher/k3s/agent/kubeproxy.kubeconfig"
```

Note: We can see that the outcome of `4.1.3` is the same when using the `$proxykubeconfig` (declared in k3s-cis-1.7-permissive/config.yaml) or the `/var/lib/rancher/k3s/agent/kubeproxy.kubeconfig`.

### To Do

For each distribution (rke, rke2 and k3s):

- [ ] Identify the details (variables) listed in [kube-bench's default config.yaml](https://github.com/aquasecurity/kube-bench/blob/main/cfg/config.yaml):

        - [ ] MASTER
            - [ ] components
            - [ ] kubernetes
                - [ ] defaultconf
            - [ ] apiserver
                - [ ] bins
                - [ ] confs
                - [ ] defaultconf
            - [ ] scheduler
                - [ ] bins
                - [ ] confs
                - [ ] defaultconf
                - [ ] kubeconfig
                - [ ] defaultkubeconfig
            - [ ] controllermanager
                - [ ] bins
                - [ ] confs
                - [ ] defaultconf
                - [ ] kubeconfig
                - [ ] defaultkubeconfig 
            - [ ] etcd
                - [ ] optional
                - [ ] bins
                - [ ] datadirs
                - [ ] confs
                - [ ] defaultconf
                - [ ] defaultdatadir
            - [ ] flanneld
                - [ ] optional
                - [ ] bins
                - [ ] defaultconf 
            - [ ] kubelet
                - [ ] optional
                - [ ] bins

        - [ ] NODE
            - [ ] components
            - [ ] kubernetes
                - [ ] defaultconf
            - [ ] kubelet
                - [ ] cafile
                - [ ] svc
                - [ ] bins
                - [ ] kubeconfig
                - [ ] confs
                - [ ] defaultconf
                - [ ] defaultsvc
                - [ ] defaultkubeconfig
                - [ ] defaultcafile
            - [ ] proxy
                - [ ] optional
                - [ ] bins
                - [ ] confs
                - [ ] kubeconfig
                - [ ] svc
                - [ ] defaultconf
                - [ ] defaultkubeconfig
        - [ ] ETCD
            - [ ] components
            - [ ] apiserver
                - [ ] bins
        - [ ] POLICIES
            - [ ] components
        - [ ] MANAGEDSERVICES
            - [ ] components

- [ ] Edit cfg/profile(permissive/hardened)/config.yaml with the listed values (if present).
