### ISSUE TITLE
Status of a "Passed" CIS v2 scan is seen in red background color

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#23]
**on master-head - commit id: `3ca11da829 `**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart`. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
- Create a ClusterScan CR and give in invalid value of scanProfileName
- The scan is currently stuck in "In progress" state
- Edit the clusterScan CR and give in the correct scanProfileName: rke-profile-permissive
- The scan run finishes, but the Cluster Scan is seen in state `Pass` but with a `red` background color.
<img width="1443" alt="Screen Shot 2020-09-06 at 2 51 16 PM" src="https://user-images.githubusercontent.com/26032343/92336464-d5ea2600-f055-11ea-9b0b-c3931ac5bdee.png">

- Scan CR yaml
```
apiVersion: cis.cattle.io/v1
kind: ClusterScan
metadata:
  creationTimestamp: "2020-09-06T21:34:47Z"
  generation: 2
  managedFields:
  -...... 
    manager: cis-operator
    operation: Update
    time: "2020-09-06T21:35:08Z"
  name: issue-3
  resourceVersion: "40244"
  selfLink: /apis/cis.cattle.io/v1/clusterscans/issue-3
  uid: d27a7bc2-4ee5-41dc-87eb-e1dc6778265a
spec:
  scanProfileName: rke-profile-permissive
status:
  conditions:
  - lastUpdateTime: "2020-09-06T21:35:03Z"
    status: "False"
    type: Failed
  - lastUpdateTime: "2020-09-06T21:35:03Z"
    status: "True"
    type: Created
  - lastUpdateTime: "2020-09-06T21:35:08Z"
    status: "True"
    type: RunCompleted
  - lastUpdateTime: "2020-09-06T21:35:08Z"
    status: "True"
    type: Complete
  - status: Unknown
    type: Alerted
  display:
    error: false
    message: ""
    state: pass
    transitioning: false
  lastRunScanProfileName: rke-profile-permissive
  lastRunTimestamp: "2020-09-06T21:35:03Z"
  observedGeneration: 2
  summary:
    fail: 0
    notApplicable: 34
    pass: 58
    skip: 0
    total: 92
```
**Expected Result:**
The background color of the state `Pass` should NOT be red.

**Comment by prachidamle** [comment]
@sowmyav27 can you pls attach the dashboard screenshot to this? thanks!

**Comment by sowmyav27** [comment]
I have attached in the original issue ^^^

**Comment by prachidamle** [comment]
Ok I Don't think this is a backend issue, but will sync up with UI and reassign if needed.

**Comment by vincent99** [comment]
Other than a couple specific word->color mappings (and passed isn't one of them), red `means metadata.state.error=true`.

There's something that _looks_ somewhat like a `metadata.state` in your `status`, but check what actually shows up for metadata through the Steve API.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `e919796c`**

- As a standard user Deployed CIS benchmark chart on a user cluster. images:
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.5
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.0
  sonobuoy:
    repository: rancher/sonobuoy-sonobuoy
    tag: v0.16.3
```

- Create a ClusterScan CR and give in invalid value of scanProfileName
- The scan is in "Error" state (red background)
- Edit the clusterScan CR and give in the correct scanProfileName: `rke-profile-permissive` or leave it blank `''`
- State of the scan changes to Running with `Red` background

<img width="1688" alt="Screen Shot 2020-09-14 at 2 10 34 PM" src="https://user-images.githubusercontent.com/26032343/93138889-a5793c00-f694-11ea-87fc-dd57acdbbff6.png">

- The scan run finishes, but the Cluster Scan is seen in state Pass but with a red background color.
<img width="1644" alt="Screen Shot 2020-09-14 at 2 11 51 PM" src="https://user-images.githubusercontent.com/26032343/93138893-a742ff80-f694-11ea-9eaf-ce153c0d37a1.png">

**Comment by prachidamle** [comment]
Fixes added for clearing the conditions when retrying a scan. This clears the "Failed" condition added during the first run since the profile is invalid.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `e919796c`** - issue is not seen fixed.

- As a standard user Deployed CIS benchmark chart on a user cluster. images:
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.6
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.0
  sonobuoy:
    repository: rancher/sonobuoy-sonobuoy
    tag: v0.16.3
```

- Create a ClusterScan CR and give in invalid value of scanProfileName
- The scan is in "Error" state (red background)
- Edit the clusterScan CR and give in the correct scanProfileName: `rke-profile-permissive` or leave it blank `''`
- State of the scan changes to Running displayed in green
- and the scan state is seen as `Pass`
<img width="941" alt="Screen Shot 2020-09-18 at 2 54 36 PM" src="https://user-images.githubusercontent.com/26032343/93648162-f5bb0b80-f9be-11ea-9633-955637be047a.png">
