### ISSUE TITLE
Rename rke-cis-1.5 ClusterScanBenchmarks to rke-cis-1.5-hardened

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#24]
**On master-head - commit id: `3ca11da829 `**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart`. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
- Available `ClusterScanBenchmarks` are:
<img width="1437" alt="Screen Shot 2020-09-06 at 3 15 24 PM" src="https://user-images.githubusercontent.com/26032343/92336281-d97cad80-f053-11ea-8816-b77b95f0869f.png">

**Expected**

- Can we rename rke-cis-1.5 ClusterScanBenchmarks to rke-cis-1.5-hardened ? 
- Because this will make it more obvious in the `ClusterScanReports` UI in the dashboard.

<img width="1447" alt="Screen Shot 2020-09-06 at 3 16 27 PM" src="https://user-images.githubusercontent.com/26032343/92336306-04ff9800-f054-11ea-8424-2f2698108ed7.png">

**Comment by sowmyav27** [comment]
**On master-head - commit id: `e919796c`**

- As a standard user Deployed CIS benchmark chart on a user cluster. images:
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.5
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.0
  sonobuoy:
    repository: rancher/sonobuoy-sonobuoy
    tag: v0.16.3
```
- BenchmarkVersion seen is `rke-cis-1.5-hardened`
<img width="1039" alt="Screen Shot 2020-09-14 at 1 59 39 PM" src="https://user-images.githubusercontent.com/26032343/93137774-dd7f7f80-f692-11ea-9bd9-00f280757271.png">
