### ISSUE TITLE
MaxKubernetesVersion column has no values in ClusterScanBenchmarks in Dashboard

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#25]
**On master-head - commit id: `3ca11da829 `**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart`. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
- In Dashboard navigate to `ClusterScanBenchmarks` 
- MaxKubernetesVersion column has no values
<img width="1437" alt="Screen Shot 2020-09-06 at 5 58 24 PM" src="https://user-images.githubusercontent.com/26032343/92339464-1d2ee180-f06b-11ea-8c8c-e8ebc2de00b5.png">

**Question:**
- Do we need `MaxKubernetesVersion` for all Benchmarks ?
