### ISSUE TITLE
CIS v2 scan does not run on a windows cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#29]
**On master-head - commit id: `01c13f69c`**

- CIS operator chart/app images:
```
image:
        cisoperator:
          repository: rancher/cis-operator
          tag: v0.0.5
        securityScan:
          repository: rancher/security-scan
          tag: v0.2.0
        sonobuoy:
          repository: rancher/sonobuoy-sonobuoy
          tag: v0.16.3
```

- Deploy a cluster scan on a windows cluster.
- The scan CR is seen in `Running` state and the Job's pod has error `Error: ImagePullBackOff`
