### ISSUE TITLE
CIS v2 scan fails on a k3s imported cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#32]
Need to have a CIS profile for k3s that will pass all active tests by default (tests can be skipped)

on master-head - `9addfe2`

- CIS v2 scan has failures when `cis-1.5-profile` is run on k3s imported clusters
- k3s imported cluster scan summary

```
summary:
    fail: 92
    notApplicable: 0
    pass: 0
    skip: 0
    total: 92
```
