### ISSUE TITLE
CIS v2: ClusterScan Operator should be able to run CIS scan on an eks/gke clusters

### ISSUE THREAD

**Issue by prachidamle** [rancher/cis-operator#7]
CISv2: clusterscan-operator 
- Should be able to run the kube-bench eks benchmark on an EKS cluster
- Should be able to run the kube-bench eks benchmark on a GKE cluster

The upstream kube-bench eks-1.0 and gke-1.0 should be added to the rancher/security-scan repo to be able to run the scan on these clustertypes.

**Comment by prachidamle** [comment]
This functionality is provided by the CIS v2 chart and cis-operator

**Comment by sowmyav27** [comment]
**On master-head - commit id: `3ca11da829 ` and `76c26fb0f9`**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart`. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
 - Deploy a GKE cluster.
- run scan by creating a scan CR `scanProfileName` is `''` 
- The default scan run on the cluster is: `gke-1.0`
- Summary of scan 
```
summary:
    fail: 44
    notApplicable: 0
    pass: 4
    skip: 0
    total: 48
```
 - Deploy an EKS cluster.
- run scan by creating a scan CR `scanProfileName` is `''` 
- The default scan run on the cluster is: `eks-1.0`
- Summary of scan : 
```
summary:
    fail: 10
    notApplicable: 0
    pass: 4
    skip: 0
    total: 14
```
