### ISSUE TITLE
CIS v2 - Prometheus Rules created for a scan when alerts are disabled

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#76]
**On 2.5-head - commit id: `baf4867` with latest cis v2 charts: `rancher-cis-benchmark:1.0.300`**

- Deploy CIS v2 app, disable alerts, alerts: false.
- Create Scan CRs
- Prometheus rules are created for this scan CR.
- No alerts are fired.

Question:
Why are Prometheus rules created when alerts: false , disabled ?

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `e2295c6 ` using cis v2 app v1.0.3**

```
cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.3-rc4
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.2-rc4
```

- Deploy CIS v2 app, disable alerts, alerts: false.
- Create Scan CRs
- Prometheus rules are created for this scan CR.
- No alerts are fired.
