### ISSUE TITLE
User with cis-admin role has no scan profile listed as default in dropdown while creating a scan

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#83]
**On 2.5-head - commit id: `bb69b03 `**

```
cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.3-rc5
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.2-rc5
```

- Deploy CIS v2 on a cluster. 
- Add a user `user1` with cis-admin role and as `cluster-member` of the cluster
- Login as `user1`
- Create a scan CR
- User with cis-admin role has no scan profile listed as default in dropdown while creating a scan
