### ISSUE TITLE
default scan profile for a k8s 1.15 cluster is incorrect

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#84]
**On 2.5-head - commit id: `48254f944 ` and ui-dashbaord-index pointing to: `releases.rancher.com/dashboard/release-2.5.4`**

```
cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.3-rc5
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.2-rc5
```

- Deploy CIS v2 on a cluster. k8s v 1.15
- The Create scan CR
- Default scan profile is CIS 1.5 instead of rke permissive 1.5 profile
<img width="840" alt="Screen Shot 2020-12-23 at 3 01 00 PM" src="https://user-images.githubusercontent.com/26032343/103043504-e4d7e400-4531-11eb-90c7-932115ab653b.png">

**Comment by sowmyav27** [comment]
As per @mantis-toboggan-md 's comments: `The issue I'm having picking a default profile on the UI side is that for this 1.15 RKE cluster, the default-clusterscanprofiles configmap shows rke: rke-profile-permissive-1.6 which is not a valid profile for 1.15`

**Comment by prachidamle** [comment]
@mantis-toboggan-md I have added PR to fix the `default-clusterscanprofiles configmap` to carry multi-line value for the key `rke` as follows:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: default-clusterscanprofiles
  namespace: {{ template "cis.namespace" . }}
data:
  # Default ClusterScanProfiles per cluster provider type
  rke: |-
    <1.16.0: rke-profile-permissive-1.5
    >=1.16.0: rke-profile-permissive-1.6
  rke2: "rke2-cis-1.5-profile-permissive"
  eks: "eks-profile"
  gke: "gke-profile"
  default: "cis-1.6-profile"
```

Thus this Configmap will carry the  default rke profiles mapped to the k8s major version to be used. Can UI read this info and show appropriate profile that matches the given cluster's k8sversion?

**Comment by sowmyav27** [comment]
On 2.5-head - commit id: `fc09f274`

- CIS operator tag:
```
cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.3-rc6
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.2-rc5
  sonobuoy:
    repository: rancher/sonobuoy-sonobuoy
    tag: v0.16.3
```

- Deploy CIS v2 on a cluster. k8s v 1.15
- The Create scan CR
- Default scan profile is rke permissive 1.5 profile
- Deploy a cluster - k8s 1.19
- Create a scan CR --> Default scan profile is rke profile permissive 1.6
