### ISSUE TITLE
CIS v2: Add an independent Operator that can deploy jobs to run CIS scan on an rke cluster

### ISSUE THREAD

**Issue by prachidamle** [rancher/cis-operator#9]
CISv2: clusterscan-operator
1. Should be deployable without rancher as a helm chart into any cluster
2. It is installed in a single cluster and can only scan that single cluster
3. The operator should just create Jobs and not deploy a helm chart for each scan.
4. Should be able to run rke permissive  and hardened scans

**Comment by prachidamle** [comment]
This has been fixed using the cis-operator and CIS v2 chart.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `76c26fb0f9`**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart`. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
- User is able to run rke permissive and hardened scans
- Chart is deployed in a single cluster, and the scan runs on that cluster only.
