### ISSUE TITLE
Redundant message shown when scan is running and reporting

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#99]
**On master-head commit id: `3e44415`**

- Scan image:
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.5-rc1
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.3
```
- repo commit:
```
status:
  branch: dev-v2.6
  commit: f9e7b6487acf45d655d6b3140bfd397988ce0357
```
- Redundant message seen when a scan is running. The status of the scan conveys it. Additional message seen is not required.

<img width="775" alt="Screen Shot 2021-07-05 at 8 55 11 PM" src="https://user-images.githubusercontent.com/26032343/124540053-82f71180-ddd3-11eb-90f5-fcfcacad8650.png">
